[processes]
web = treamlit run app.py

[[services]]
  processes = ["web"] # this service only applies to the web process
  http_checks = []
  internal_port = 8501
  protocol = "tcp"
  script_checks = []